version: '3.9'  # Use the correct version

services:
  web:
    build: .  # Build from the Dockerfile in the current directory
    ports:
      - "8000:8000"  # Expose port 8000 on the host, mapping to port 8000 in the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container for live changes
    environment:
      - DEBUG=True  # Set environment variable; adjust based on your needs
    command: python manage.py runserver 127.0.0.1:8000  # Start the Django development server
